image:
  file: .gitpod.Dockerfile

tasks:
  - init: bundle install
    command: rails server

# exposed ports
ports:
- port: 8080
  onOpen: open-preview
  visibility: public
- port: 5432
  onOpen: ignore

vscode:
  extensions:
    - rebornix.Ruby
